### ISSUE TITLE
Deploy the Delivery Tracker V2 (2023.11.11)

### ISSUE THREAD

**Issue by shlee322** [shlee322/delivery-tracker#185]
## Progress
- [x] Step 1. Deploy the Delivery Tracker V2 System.
- [x] Step 2. Deploy the Delivery Tracker V1 Compatible Layer.
- [x] Step 3. V1 Compatible Layer Canary Testing.
- [x] Step 4. Switch the Delivery Tracker V2 Core from private to public.

**Comment by shlee322** [comment]
v2023.1 배포로 해당 작업들이 완료되어 close 합니다.
