### ISSUE TITLE
Add Carriers (Sprint-1)

### ISSUE THREAD

**Issue by shlee322** [shlee322/delivery-tracker#22]
**Carriers List**
- [x] CJ대한통운 (kr.cjlogistics)
- [x] CU 편의점택배 (kr.cupost)
- [x] CVSnet 편의점택배 (kr.cvsnet)
- [x] Cway Express (kr.cway #24)
- [x] DHL (de.dhl #36)
- [ ] DHL Global Mail (de.dhl.ecommerce)
- [ ] ECMS Express ()
- [x] EMS (un.upu.ems #38)
- [x] Fedex (us.fedex #39)
- [ ] GSI Express (us.gsiexpress)
- [ ] GSMNtoN (kr.gsmnton)
- [ ] i-Parcel (us.i-parcel)
- [x] SLX (kr.slx #46)
- [x] TNT Express (nl.tnt #44)
- [x] UPS (us.ups #40)
- [x] USPS (us.usps #41)
- [x] 건영택배 (kr.kunyoung #35)
- [x] 경동택배 (kr.kdexp #34)
- [x] 대신택배 (kr.daesin #37)
- [x] 로젠택배 (kr.logen)
- [x] 롯데택배 (kr.lotte)
- [ ] 성원글로벌카고 (kr.swgexp)
- [ ] 에어보이익스프레스 (us.airboyexpress)
- [x] 우체국택배 (kr.epost)
- [ ] 워펙스코리아 (us.warpex)
- [x] 일양로지스 (kr.ilyanglogis #33)
- [x] 천일택배 (kr.chunilps #32)
- [ ] 판토스 (kr.pantos)
- [x] 한의사랑택배 (kr.hanips #47)
- [x] 한진택배 (kr.hanjin)
- [x] 합동택배 (kr.hdexp #31)
- [x] 한서호남택배 (kr.honamlogis #30)
- [x] 홈픽택배 (kr.homepick #29)

**Excepted**
- KGB택배 : 자금난으로 운영 중단 상태으로 파악됨
- KGL네트웍스 : 홈페이지 내에 배송조회 기능을 찾을 수 없음
- 한덱스 : 한진택배와 통합
- 굿투럭 : 사이트 500 에러
- YJS글로벌(영국)
- 세방 : 배송조회 기능 찾을 수 없음
- 우리한방택배 : 운송장 번호 취득까지 보류
- 은하쉬핑 (kr.ieunha) : 운송장 번호 취득까지 보류
- 하이택배 : 운송장 번호 취득까지 보류
- 홈이노베이션로지스
